export function coinListManage() {
  const coinList = ref({
    USDT: [
      {
        name: 'usdt',
        coin: 'usdt',
        days: '7',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '0.8%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'usdt',
        coin: 'usdt',
        days: '15',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '0.9%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'usdt',
        coin: 'usdt',
        days: '30',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'usdt',
        coin: 'usdt',
        days: '90',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1.1%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'usdt',
        coin: 'usdt',
        days: '180',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1.2%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'usdt',
        coin: 'usdt',
        days: '360',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1.3%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
    ],
    WT: [
      {
        name: 'wt',
        coin: 'wt',
        days: '7',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '0.9%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'wt',
        coin: 'wt',
        days: '15',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'wt',
        coin: 'wt',
        days: '30',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1.1%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'wt',
        coin: 'wt',
        days: '90',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1.2%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'wt',
        coin: 'wt',
        days: '180',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1.3%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
      {
        name: 'wt',
        coin: 'wt',
        days: '360',
        balance: '0',
        deposited: '0',
        redeemable: '0',
        income: '0',
        rate: '1.4%',
        children: [
          {
            name: 'subscribe',
            value: '',
            placeholder: '先启用',
            text: '认购',
          },
          {
            name: 'redemption',
            value: '',
            placeholder: '请输入赎回数量',
            text: '赎回',
          },
          {
            name: 'burning',
            value: '',
            placeholder: '请输入燃烧数量',
            text: '燃烧WT',
          },
        ],
      },
    ],
  });
  return {
    coinList,
  };
}
